#!/bin/zsh -fuC

if [[ -e ~/.config/mx-tools.rc ]]
then
    . ~/.config/mx-tools.rc
fi

# poor mens test if value is set
: $auth_token $server_url $db_name

if [[ $# -lt 1 ]]
then
    # TODO: bessere Meldung
    echo "ARG missing" >&2
    exit 1
fi

user_id=$1

psql -X -c "
SELECT to_timestamp(origin_server_ts / 1000) AS time,
  coalesce(canonical_alias, room_id) as room
FROM events
NATURAL JOIN room_stats_state
WHERE sender = '$user_id' AND type = 'm.room.member'
ORDER BY time
" $db_name \
    || exit
